### PR TITLE
Big refactor of oracle module out into seperate eth bridge module

### PR DESCRIPTION
**Pull request by musnit**
note - some tests still need to be fixes, and small issue with querier

### CODE REVIEW

**Comment by musnit** [comment]
all fixed now

**Review by denalimarsh — APPROVED** [review]
Approving substantial changes to new module and required integration with legacy code. Let's refine the separation of responsibilities between the two modules once mvp is functional.

**Review by denalimarsh — APPROVED** [review]
Approved, but soon we will need to test `MinimumPower` requirements in `querier_test.go`. Thoughts on mocking some data for a quick test setup here vs getting other validator processes tested first?

**Comment by musnit** [comment]
@denalimarsh i'm leaving the power/validator tests for after MVP

**Pull request merged**
