### PR TITLE
More tests

### PR DESCRIPTION
**Pull request by musnit**
- Add checks on handler for ethereum nonce/address
 - Add more comprehensive tests

### CODE REVIEW

**Review by denalimarsh — APPROVED** [review]
Initial handler tests approved

**Review by denalimarsh — APPROVED** [review]
Initial querier tests approved

**Review by denalimarsh — APPROVED** [review]
Keeper tests looks good. Glad to see the test suite coming together.

**Comment by musnit** [comment]
Closing, as commits were included in merge of future PR: https://github.com/swishlabsco/cosmos-ethereum-bridge/pull/9

**Pull request closed without merging**
